# Generated by Django 5.2.6 on 2025-10-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusevents', '0002_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='admin_comment',
            field=models.TextField(blank=True, help_text='Admin comment when rejecting or modifying event', null=True),
        ),
    ]
