# Generated by Django 5.2.6 on 2025-10-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusevents', '0004_event_created_at_event_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
