name: CI (pytest + pylint)

on:
  push:
  pull_request:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install project (with dev extras)
        run: |
          pip install -e .[dev]
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run pytest
        # run: pytest -q

      - name: Run pylint
        # run: pylint ./campus ./campusevents --fail-under=8
